package org.rust.cargo.project.settings

import com.intellij.openapi.externalSystem.settings.ExternalSystemSettingsListener

interface CargoProjectSettingsListener : ExternalSystemSettingsListener<CargoProjectSettings>
